<?php

namespace Database\Seeders;

use App\Models\Film;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class FilmsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $films = [
            [
                'author' => 'LatvijasKino',
                'category' => 1,
                'filmname' => 'Catch her in rye',
                'genre' => 'Horror',
                'volume' => 50,
                'text' => 'None',
            ],
            [
                'author' => 'LatvijasKino',
                'model' => 'Budget',
                'year' => 2018,
                'duration' => 165,
                'filmname' => 'Rotten boobs in Cassiopia',
                'genre' => 'Horror',
                'volume' => 39,
                'description' => 'None',
                'price_per_subscribtion' => 6,
                'price_per_watch' => 4,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'LatvijasKino',
                'model' => 'Budget',
                'year' => 2018,
                'duration' => 120,
                'filmname' => 'Epic Crossover',
                'genre' => 'Comedy',
                'volume' => 136,
                'description' => 'None',
                'price_per_subscribtion' => 6,
                'price_per_watch' => 1,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'BEBRAPRODUCTION',
                'model' => 'Blockbuster',
                'year' => 2018,
                'duration' => 150,
                'filmname' => 'Smell',
                'genre' => 'Thriller',
                'volume' => 134,
                'description' => 'None',
                'price_per_subscribtion' => 24,
                'price_per_watch' => 7,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => 'filmImages/images.jpeg',
                'filmImage8' => null,
            ],
            [
                'author' => 'BEBRAPRODUCTION',
                'model' => 'Blockbuster',
                'year' => 2020,
                'duration' => 150,
                'filmname' => 'Nigga in paris',
                'genre' => 'Thriller',
                'volume' => 91,
                'description' => 'None',
                'price_per_subscribtion' => 24,
                'price_per_watch' => 5,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => 'filmImages/images.jpeg',
                'filmImage8' => null,
            ],
            [
                'author' => 'BEBRAPRODUCTION',
                'model' => 'Budget',
                'year' => 2021,
                'duration' => 100,
                'filmname' => 'Estate',
                'genre' => 'Comedy',
                'volume' => 156,
                'description' => 'None',
                'price_per_subscribtion' => 24,
                'price_per_watch' => 10,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => null,
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'Bangbros',
                'model' => 'Budget',
                'year' => 2018,
                'duration' => 275,
                'filmname' => 'Base',
                'genre' => 'ActionMovie',
                'volume' => 110,
                'description' => 'None',
                'price_per_subscribtion' => 24,
                'price_per_watch' => 11,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => 'filmImages/images.jpeg',
                'filmImage8' => 'filmImages/images.jpeg',
            ],
            [
                'author' => 'Bangbros',
                'model' => 'Budget',
                'year' => 2020,
                'duration' => 13,
                'filmname' => 'Short reminder that smoking is cool',
                'genre' => 'ActionMovie',
                'volume' => 0,
                'description' => 'None',
                'price_per_subscribtion' => 24,
                'price_per_watch' => 4,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => 'filmImages/images.jpeg',
                'filmImage8' => null,
            ],
            [
                'author' => 'WarnerBrazzers',
                'model' => 'Blockbustrer',
                'year' => 2020,
                'duration' => 150,
                'filmname' => 'Meme Lord',
                'genre' => 'Horror',
                'volume' => 151,
                'description' => 'None',
                'price_per_subscribtion' => 23,
                'price_per_watch' => 5,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'Unknown',
                'model' => 'Blockbuster',
                'year' => 2022,
                'duration' => 136,
                'filmname' => 'Slickback',
                'genre' => 'Horror',
                'volume' => 113,
                'description' => 'None',
                'price_per_subscribtion' => 23,
                'price_per_watch' => 5,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => 'filmImages/images.jpeg',
                'filmImage8' => null,
            ],
            [
                'author' => 'BEBRAPRODUCTION',
                'model' => 'Blockbuster',
                'year' => 2005,
                'duration' => 100,
                'filmname' => 'Giga nigga',
                'genre' => 'Horror',
                'volume' => 175,
                'description' => 'None',
                'price_per_subscribtion' => 24,
                'price_per_watch' => 0.22,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => null,
                'filmImage5' => null,
                'filmImage6' => null,
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'CRAP',
                'model' => 'Budget',
                'year' => 2020,
                'duration' => 179,
                'filmname' => 'Slow Murder',
                'genre' => 'Horror',
                'volume' => 86,
                'description' => 'None',
                'price_per_subscribtion' => 2,
                'price_per_watch' => 1,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'JackiechanFilms',
                'model' => 'Blockbuster',
                'year' => 2021,
                'duration' => 99,
                'filmname' => 'Jackie Chan 18',
                'genre' => 'Action',
                'volume' => 101,
                'description' => 'None',
                'price_per_subscribtion' => 25,
                'price_per_watch' => 9,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => null,
                'filmImage8' => null,
            ],
            [
                'author' => 'Twentycentuaryfox',
                'model' => 'Blockbuster',
                'year' => 2021,
                'duration' => 286,
                'filmname' => 'Drive 2',
                'genre' => 'Thriller',
                'volume' => 181,
                'description' => 'None',
                'price_per_subscribtion' => 89,
                'price_per_watch' => 23,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => 'filmImages/images.jpeg',
                'filmImage7' => 'filmImages/images.jpeg',
                'filmImage8' => null,
            ],
            [
                'author' => 'RealityKings',
                'model' => 'Budget',
                'year' => 2022,
                'duration' => 131,
                'filmname' => 'Dum Dum',
                'genre' => 'Horror',
                'volume' => 143,
                'description' => 'None',
                'price_per_subscribtion' => 17,
                'price_per_watch' => 9,
                'filmImage1' => 'filmImages/images.jpeg',
                'filmImage2' => 'filmImages/images.jpeg',
                'filmImage3' => 'filmImages/images.jpeg',
                'filmImage4' => 'filmImages/images.jpeg',
                'filmImage5' => 'filmImages/images.jpeg',
                'filmImage6' => null,
                'filmImage7' => null,
                'filmImage8' => null,
            ],
        ];

        foreach ($films as $film) {
            Film::create($film);
        }
    }
}
